# Generated by Django 6.0 on 2025-12-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="datecompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
