# Generated by Django 6.0 on 2025-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio", "0002_task_completed_alter_task_datecompleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="task",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="task_documents/"),
        ),
    ]
